name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws configure set region eu-west-1
          aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 039612856398.dkr.ecr.eu-north-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .
          docker tag flask-app:latest 039612856398.dkr.ecr.eu-north-1.amazonaws.com/flask-app:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 039612856398.dkr.ecr.eu-north-1.amazonaws.com/flask-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to EC2 instance
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "${{ secrets.ANSIBLE_SSH_KEY }}" > ansible_key.pem
          chmod 600 ansible_key.pem
          ssh -o StrictHostKeyChecking=no -i ansible_key.pem ec2-user@13.51.85.114 <<EOF
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set region eu-west-1
            aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 039612856398.dkr.ecr.eu-north-1.amazonaws.com
            docker pull 039612856398.dkr.ecr.eu-north-1.amazonaws.com/flask-app:latest
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 5000:5000 --name flask-app 039612856398.dkr.ecr.eu-north-1.amazonaws.com/flask-app:latest
          EOF
